export const headerArray = [
  { title: 'МИНИМАЛЬНАЯ СУММА ЗАКАЗА - 8000 ₽' },
  { title: 'КАЧЕСТВЕННЫЕ ВЕЩИ' },
  { title: 'БЫСТРАЯ ДОСТАВКА' },
  { title: 'БОЛЬШИЕ СКИДКИ' },
];

export const cardArray = [
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: 'новинка',
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
  {
    title: 'Футболка “Пионер”',
    years: '2-4 лет',
    type: null,
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '900',
  },
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: 'новинка',
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: null,
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: null,
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: 'новинка',
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: 'новинка',
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: 'новинка',
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: 'новинка',
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: 'новинка',
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: 'новинка',
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: 'новинка',
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: 'новинка',
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: 'новинка',
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: 'новинка',
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
  {
    title: 'Футболка “Радуга”',
    years: '2-4 лет',
    type: 'новинка',
    article: '1111',
    height: '54-56',
    priceOf: 'за 10 шт',
    size: '1-7',
    price: '1300',
  },
];

export const accordionArray = [
  {
    question: 'С какими брендами вы сотрудничаете?',
    answer: 'Sim-Sim, Звездочка, Sabah, Zari for kids, Zeyrek, Gavhar, Nuriya',
  },
  {
    question: 'Какая минимальная сумма заказа?',
    answer: 'оставка платная Зависит от веса, габарита и прочие факторы',
  },
  {
    question: 'Способы оплаты?',
    answer: 'Способ оплаты Переводом на карту Со счёта на счёт',
  },
  {
    question: 'Какие данные будете брать с заказчика для заказа?',
    answer: 'Sim-Sim, Звездочка, Sabah, Zari for kids, Zeyrek, Gavhar, Nuriya',
  },
  {
    question: 'Список городов и стран для доставки?',
    answer: 'оставка платная Зависит от веса, габарита и прочие факторы',
  },
  {
    question: 'Ваши социальные сети?',
    answer: 'Способ оплаты Переводом на карту Со счёта на счёт',
  },
];
